# Generated by Django 3.2.6 on 2021-08-21 22:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questiontext',
            new_name='question_text',
        ),
    ]
